In [1]:
import pandas as pd
from functools import reduce

In [2]:
df = pd.read_excel('../data/debt_lives_processed.xlsx')

In [3]:
df.describe()

,cup,start_val,debt,born,unsafe,wiped,bitten,shut,safe again,# oscillations,transition0_time,transition1_time,transition2_time,transition3_time,transition4_time,transition5_time,transition6,transition6_time,transition7_time
count,26260.000000,2.626000e+04,2.626000e+04,2.626000e+04,3.864000e+03,1.761100e+04,3.922000e+03,4.350000e+02,3.100000e+02,26260.000000,2.197600e+04,3.861000e+03,3.090000e+02,2.530000e+02,3.100000e+01,2.900000e+01,3.0,3.000000e+00,3.000000e+00
mean,3585.148629,9.017713e+03,7.317776e+03,1.536473e+09,1.537317e+09,1.537498e+09,1.536662e+09,1.530776e+09,1.534198e+09,0.170944,1.537213e+09,1.537309e+09,1.534592e+09,1.534623e+09,1.538060e+09,1.537507e+09,0.0,1.542931e+09,1.542933e+09
std,3441.430982,5.488945e+04,5.048225e+04,1.044807e+07,8.954168e+06,9.585949e+06,8.941844e+06,9.354467e+06,9.865324e+06,0.471417,9.522365e+06,8.951605e+06,9.744155e+06,9.936278e+06,1.029123e+07,1.037900e+07,0.0,0.000000e+00,1.705099e+03
min,1.000000,1.000000e-18,0.000000e+00,1.513625e+09,1.513629e+09,1.513629e+09,1.513630e+09,1.513719e+09,1.513630e+09,0.000000,1.513629e+09,1.513630e+09,1.513630e+09,1.513731e+09,1.513909e+09,1.513909e+09,0.0,1.542931e+09,1.542932e+09
25%,1219.750000,1.000000e+02,5.000000e+00,1.526679e+09,1.533739e+09,1.529754e+09,1.533257e+09,1.524039e+09,1.527152e+09,0.000000,1.529856e+09,1.533742e+09,1.527344e+09,1.527062e+09,1.534177e+09,1.534177e+09,0.0,1.542931e+09,1.542932e+09
50%,2744.500000,5.500000e+02,2.700000e+02,1.539495e+09,1.536462e+09,1.540938e+09,1.536426e+09,1.530478e+09,1.534187e+09,0.000000,1.539381e+09,1.536462e+09,1.534212e+09,1.534258e+09,1.542754e+09,1.542754e+09,0.0,1.542931e+09,1.542932e+09
75%,4663.000000,3.000000e+03,2.000000e+03,1.545773e+09,1.544144e+09,1.545833e+09,1.543119e+09,1.539662e+09,1.542697e+09,0.000000,1.545626e+09,1.544144e+09,1.542701e+09,1.542703e+09,1.543139e+09,1.543139e+09,0.0,1.542931e+09,1.542934e+09
max,14361.000000,2.499750e+06,2.499750e+06,1.549496e+09,1.549481e+09,1.549496e+09,1.549463e+09,1.549401e+09,1.549469e+09,7.000000,1.549496e+09,1.549481e+09,1.549474e+09,1.549514e+09,1.549548e+09,1.548601e+09,0.0,1.542931e+09,1.542935e+09

In [4]:
print(df.cup.nunique())
print(df.shape[0])

6467
26260

In [5]:
print(df.born.nunique())
print(df.shape[0])

25552
26260

In [6]:
max_ts = df.born.max()

In [7]:
df['# oscillations'].value_counts()

0    22399
1     3552
3      222
2       56
5       26
7        3
4        2
Name: # oscillations, dtype: int64

In [8]:
states = ['born', 'unsafe', 'safe again', 'wiped', 'bitten', 'shut']

In [9]:
state_matrix = pd.notnull(df[states]) # create state matrix where 1 indicates that CDP entered this state
state_matrix.head() # show what the matrix looks like - first 5 rows

   born  unsafe  safe again  wiped  bitten   shut
0  True   False       False  False   False  False
1  True   False       False  False   False  False
2  True   False       False  False   False  False
3  True   False       False   True   False  False
4  True   False       False  False   False  False

In [10]:
state_matrix.sum() / state_matrix.count() # what fraction of CDPs enter each state?

born          1.000000
unsafe        0.147144
safe again    0.011805
wiped         0.670640
bitten        0.149353
shut          0.016565
dtype: float64

In [11]:
tmp = state_matrix.copy()
tmp['p'] = 1
p_sequence = tmp.groupby(states).count() / tmp['p'].count()
p_sequence

                                                  p
born unsafe safe again wiped bitten shut
True False  False      False False  False  0.163138
                                    True   0.016489
                             True   False  0.015994
                       True  False  False  0.657235
     True   False      False False  False  0.000114
                                    True   0.000038
                             True   False  0.122163
                       True  False  False  0.013024
            True       False False  False  0.000190
                                    True   0.000038
                             True   False  0.011196
                       True  False  False  0.000381

In [ ]:
pd.Series([' -> '.join(s) for s in sorted_sequences]).value_counts(normalize=1)